// frontend/src/app/app.component.ts
import { Component, computed, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { TodoService } from './todo.service';
import { TodoItem } from './todo.model';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  todos = signal<TodoItem[]>([]);
  newTask = signal('');
  loading = signal(true);
  error = signal('');

  completedCount = computed(() => this.todos().filter((t) => t.completed).length);

  constructor(private todoService: TodoService) {}

  ngOnInit(): void {
    this.fetchTodos();
  }

  fetchTodos(): void {
    this.loading.set(true);
    this.error.set('');
    this.todoService.getAll().subscribe({
      next: (data) => {
        this.todos.set(data);
        this.loading.set(false);
      },
      error: () => {
        this.error.set('Failed to load tasks');
        this.loading.set(false);
      }
    });
  }

  addTodo(event: Event): void {
    event.preventDefault();
    const title = this.newTask().trim();
    if (!title) return;

    this.error.set('');
    this.todoService.create(title).subscribe({
      next: (created) => {
        this.todos.update((list) => [...list, created]);
        this.newTask.set('');
      },
      error: () => this.error.set('Could not add task')
    });
  }

  toggleTodo(id: number): void {
    this.error.set('');
    this.todoService.toggle(id).subscribe({
      next: (updated) =>
        this.todos.update((list) =>
          list.map((t) => (t.id === id ? updated : t))
        ),
      error: () => this.error.set('Could not update task')
    });
  }

  deleteTodo(id: number): void {
    this.error.set('');
    this.todoService.delete(id).subscribe({
      next: () => this.todos.update((list) => list.filter((t) => t.id !== id)),
      error: () => this.error.set('Could not delete task')
    });
  }
}

<main class="page">
  <section class="todo-card">
    <h1>To-Do List</h1>
    <p class="subtitle">{{ todos().length }} tasks, {{ completedCount() }} completed</p>

    <form (ngSubmit)="addTodo($event)" class="todo-form">
      <input
        type="text"
        placeholder="Add a task..."
        [value]="newTask()"
        (input)="newTask.set($any($event.target).value)"
      />
      <button type="submit">Add</button>
    </form>

    @if (error()) {
      <p class="error">{{ error() }}</p>
    }

    @if (loading()) {
      <p class="status">Loading tasks...</p>
    } @else if (todos().length === 0) {
      <p class="status">No tasks yet. Add your first one.</p>
    } @else {
      <ul class="todo-list">
        @for (todo of todos(); track todo.id) {
          <li [class.done]="todo.completed">
            <label>
              <input
                type="checkbox"
                [checked]="todo.completed"
                (change)="toggleTodo(todo.id)"
              />
              <span>{{ todo.title }}</span>
            </label>
            <button (click)="deleteTodo(todo.id)">Delete</button>
          </li>
        }
      </ul>
    }
  </section>
</main>

// frontend/src/App.jsx
import { useEffect, useMemo, useState } from 'react';

const API_URL = 'http://localhost:8080/api/todos';

function App() {
  const [todos, setTodos] = useState([]);
  const [newTask, setNewTask] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const completedCount = useMemo(
    () => todos.filter((todo) => todo.completed).length,
    [todos]
  );

  const fetchTodos = async () => {
    try {
      setLoading(true);
      setError('');
      const response = await fetch(API_URL);
      if (!response.ok) {
        throw new Error('Failed to load tasks');
      }
      const data = await response.json();
      setTodos(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTodos();
  }, []);

  const addTodo = async (event) => {
    event.preventDefault();
    const title = newTask.trim();
    if (!title) {
      return;
    }

    try {
      setError('');
      const response = await fetch(API_URL, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title })
      });

      if (!response.ok) {
        throw new Error('Could not add task');
      }

      const created = await response.json();
      setTodos((current) => [...current, created]);
      setNewTask('');
    } catch (err) {
      setError(err.message);
    }
  };

  const toggleTodo = async (id) => {
    try {
      setError('');
      const response = await fetch(`${API_URL}/${id}/toggle`, {
        method: 'PUT'
      });

      if (!response.ok) {
        throw new Error('Could not update task');
      }

      const updated = await response.json();
      setTodos((current) =>
        current.map((todo) => (todo.id === id ? updated : todo))
      );
    } catch (err) {
      setError(err.message);
    }
  };

  const deleteTodo = async (id) => {
    try {
      setError('');
      const response = await fetch(`${API_URL}/${id}`, {
        method: 'DELETE'
      });

      if (!response.ok && response.status !== 204) {
        throw new Error('Could not delete task');
      }

      setTodos((current) => current.filter((todo) => todo.id !== id));
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <main className="page">
      <section className="todo-card">
        <h1>To-Do List</h1>
        <p className="subtitle">
          {todos.length} tasks, {completedCount} completed
        </p>

        <form onSubmit={addTodo} className="todo-form">
          <input
            type="text"
            placeholder="Add a task..."
            value={newTask}
            onChange={(event) => setNewTask(event.target.value)}
          />
          <button type="submit">Add</button>
        </form>

        {error && <p className="error">{error}</p>}

        {loading ? (
          <p className="status">Loading tasks...</p>
        ) : todos.length === 0 ? (
          <p className="status">No tasks yet. Add your first one.</p>
        ) : (
          <ul className="todo-list">
            {todos.map((todo) => (
              <li key={todo.id} className={todo.completed ? 'done' : ''}>
                <label>
                  <input
                    type="checkbox"
                    checked={todo.completed}
                    onChange={() => toggleTodo(todo.id)}
                  />
                  <span>{todo.title}</span>
                </label>
                <button onClick={() => deleteTodo(todo.id)}>Delete</button>
              </li>
            ))}
          </ul>
        )}
      </section>
    </main>
  );
}

export default App;
